### ISSUE TITLE
Error: drawtext is not a function

### ISSUE THREAD

**Issue by Shashwatsh** [yue/yue#70]
```  painter.drawtext("Hello, World", {X:0, Y:0, Width:100, Height:500}, {color: "#008000"})```

```          ^

TypeError: painter.drawtext is not a function
    at drawSquare (/Users/shashwat/Documents/mos6502/mos6502.js:14:11)
    at Function.contentview.onDraw (/Users/shashwat/Documents/mos6502/mos6502.js:20:2)
```

i'm getting this error when calling drawtext function

**Comment by Shashwatsh** [comment]
changed drawtext to drawText(). everything working now
